#ifndef _SYSTEM_PLAT_COMMON_H_

#define _SYSTEM_PLAT_COMMON_H_

#define VPSS_ENLARGE_GRP_CHN_0		20
#define VPSS_ENLARGE_GRP_CHN_1		21
#define VPSS_THUMBNAIL_GRP_CHN_0	0
#define VPSS_THUMBNAIL_GRP_CHN_1	2

#define ISM_5030D_INPUT_DUP_CHG     1



#endif /* _SYSTEM_PLAT_COMMON_H_ */

