#ifndef __HIK_APT_ERR_H__
#define __HIK_APT_ERR_H__

#define HIK_APT_TRUE    1
#define HIK_APT_FALSE   0

#define HIK_APT_S_OK    1
#define HIK_APT_S_FAIL  0
#define HIK_APT_ERR_INVALID_PARAM    0x8DBA1001
#define HIK_APT_ERR_NULL_PTR         0x8DBA1002

#define HIK_APT_MEM_INVALID_ATTR     0x8DBD1001
#define HIK_APT_MEM_INVALID_PLAT     0x8DBD1002
#define HIK_APT_MEM_INVALID_ALIGN    0x8DBD1003
#define HIK_APT_MEM_LACK_OF_MEM      0x8DBD1004
#define HIK_APT_MEM_INVALID_SPACE    0x8DBD1005

#define HIK_APT_JSON_NULL_PTR          0x8DBE1001
#define HIK_APT_JSON_FILE_LEN          0x8DBE1002
#define HIK_APT_JSON_PARAM_ERR         0x8DBE1003
#endif